### PR TITLE
Update enabling-stream-support-b236d32.md

### PR DESCRIPTION
**Pull request by katansapdevelop**
The current link to the CAP Documentation is broken. I have a updated with a proposed alternative

### CODE REVIEW

**Comment by KvM2** [comment]
Hi @katansapdevelop, thanks for your contribution! We'll look into it and get back to you.

**Comment by mishuagrawal** [comment]
Hello @katansapdevelop,

Thank you for bringing this to our notice. Please know that we have now replaced the non-working link with the correct one. However, the reflection of the change may take some time. The documentation will be updated post our current release. 

If in case you have any further concerns, please do let us know. If your concern is resolved, kindly go ahead and close this request or let us know if we can do so.

Thanks and regards,
Mishu Agrawal

**Comment by mishuagrawal** [comment]
Hello @katansapdevelop,

We have now updated the link and you can check it here: https://ui5.sap.com/1.127.0/#/topic/b236d32d48b74304887b3dd5163548c1

Kindly confirm if your concern is resolved and if we can go ahead and close this request. 

Thanks and regards,
Mishu Agrawal

**Comment by katansapdevelop** [comment]
Hi @mishuagrawal , I've just had a look and link is now working perfectly.
image

image

Thanks for fixing it up

**Comment by mishuagrawal** [comment]
Hello @katansapdevelop,

Thank you for the confirmation. I am going to go ahead and close this request now. Please feel free to reach out to us if you have any further concerns in the future.

Thanks and regards,
Mishu Agrawal

**Pull request merged**
