### PR TITLE
Remove restriction to V2

### PR DESCRIPTION
**Pull request by drktfl**
There is a discrepancy between this page and https://ui5.sap.com/#/topic/965ef5b2895641bc9b6cd44f1bd0eb4d

### CODE REVIEW

**Comment by KvM2** [comment]
Hi Dirk, thanks for your contribution. We appreciate it and will look into this.

**Comment by JannaLisa** [comment]
Hi @drktfl ,

I've made some changes to the topic that will hopefully resolve the confusion.
The change will be visible with release 1.110.

Thanks!

**Comment by JannaLisa** [comment]
Hi @drktfl ,
Could you please check if the topic is fine now for you?
If so, please close this issue.

**Comment by drktfl** [comment]
thanks! looks fine now.

**Pull request closed without merging**
