### PR TITLE
Clarify importance of setting `compatVersion`

### PR DESCRIPTION
**Pull request by AndreCunha1**
```
configuration-options-and-url-parameters-91f2d03.md
- Clarify importance of setting `compatVersion`
```

**Reasoning:**

- If `compatVersion` is not set as expected, then the documented `bindingSyntax` default value (among other settings) does not apply (i.e. it is **not** `complex` as documented). This updated note at the top of the page helps to clarify this.

BCP: 2270148900

### CODE REVIEW

**Comment by OlMue** [comment]
Hi @AndreCunha1, thanks for your contribution! We will look into this and get back to you.

**Comment by KlattG** [comment]
Fixed from 1.110

**Comment by AndreCunha1** [comment]
> Thank you for your valuable content contribution, @AndreCunha1! So that we can [recognize your contribution in SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:
> 
> ```
> https://people.sap.com/your-user-name
> ```
> 
> Thanks!

https://people.sap.com/andre.antunes.da.cunha

**Comment by AndreCunha1** [comment]
https://people.sap.com/andre.antunes.da.cunha

**Pull request merged**
