### PR TITLE
add missing comma is sample code

### PR DESCRIPTION
**Pull request by marianfoo**

### CODE REVIEW

**Comment by KvM2** [comment]
Hi @marianfoo, thanks for your contribution. We appreciate it and will look into this.

**Comment by JannaLisa** [comment]
Hi @marianfoo ,
happy to see our customers are reading our sample codes so precisely!
I have added the missing comma and apologize for this oversight.
The correction will be visible with release 1.110.

Thanks!

**Comment by marianfoo** [comment]
@JannaLisa 
Just out of interest:
How is the process with the pull requests in GitHub because I see many that are still open
Also this one, which should be then inserted in 1.110, is still open.
Is the PR simply taken as a basis and the changes then adopted internally?

**Comment by JannaLisa** [comment]
Hi @marianfoo ,
Maybe I need to click the 'Merge pull request' button...
I'm afraid this is still new for me and I haven't gotten the hang of it yet.
I can definitely already see the correction in our documentation, so in a few days time you will see it as well.
image

Let me click that button and then, when you see the correction, as far as I know you need to confirm and close the pull request.
Best regards,
Janna

**Pull request merged**
