### PR TITLE
Update using-messages-239b192.md

### PR DESCRIPTION
**Pull request by IAmSandeepRS**
Clean up on handling bound messages in V4 specific section

### CODE REVIEW

**Comment by IAmSandeepRS** [comment]
@MarcelWaechter Can you help check the changes here and provide a +1 if it's all fine (this is just the first bit - am also adding further changes but thought will break up the changes for faster change/merge :-))

**Comment by KvM2** [comment]
Hi @IAmSandeepRS , thanks for your contribution . We appreciate it and will look into this.

**Comment by mishuagrawal** [comment]
Checked with @IAmSandeepRS and he is going to provide further change suggestions for this topic. We will work on it when we get a go from Sandeep.

**Review by MarcelWaechter — APPROVED** [review]
Thanks, looks good to me :)

**Comment by IAmSandeepRS** [comment]
Closing this since this is covered with https://github.wdf.sap.corp/uics-innersource/ui5-docs/pull/472.

**Pull request closed without merging**
