### PR TITLE
Update using-the-multi-input-field-on-the-object-page-04ff5b1.md

### PR DESCRIPTION
**Pull request by jberthe**
Add further sample for ABAP CDS annotation to beter anderstanding how the multi-input can be integreted into a Facet.

### CODE REVIEW

**Comment by mishuagrawal** [comment]
Hello @jberthe, please know that we are working on your concern. We will get back to you as soon as we have an update.

**Comment by mishuagrawal** [comment]
Hello @jberthe,

I have updated the document with the provided information. It should start reflecting in our productive system soon. 

Thanks and regards,
 Mishu Agrawal

**Comment by mishuagrawal** [comment]
Hello @jberthe,

We had updated the document and you can review the changes here: https://ui5.sap.com/#/topic/04ff5b1a81344a8e8169ea99630ff4e5

If there are any further concerns, please feel free to reach out to us. If your concern is now resolved, please let us know.

Thanks and regards,
Mishu Agrawal

**Comment by mishuagrawal** [comment]
Hello @jberthe,

Please confirm if your concern is resolved and if we can go ahead and close this request now. 

Thanks and regards,
Mishu Agrawal

**Comment by mishuagrawal** [comment]
Hello @jberthe,

Please confirm if your concern is resolved and if we can go ahead and close this request now.

Thanks and regards,
Mishu Agrawal

**Comment by jberthe** [comment]
Hello,

I confirm all is ok. Thanks 

Regards

**Comment by mishuagrawal** [comment]
Hello @jberthe,

Thank you for the confirmation.

Best Regards,
Mishu Agrawal

**Pull request merged**
