### PR TITLE
add cap annotation sample for sideeffects examples

### PR DESCRIPTION
**Pull request by marianfoo**
A sample for the CAP Annotation is missing in this examples.

In general the formatting with:
`>     >`
is a bit strange.
Is this intentional?

### CODE REVIEW

**Comment by KvM2** [comment]
Hi @marianfoo , thanks for your contribution. We appreciate it and will look into this.

**Comment by JannaLisa** [comment]
Hi @marianfoo ,
Sorry for not responding sooner, and actually at the moment I can also only tell you that this is still work in progress.
We will try to update this next week and get back to you.

**Comment by mishuagrawal** [comment]
Hello,

Please accept my sincere apologies for responding late. Kindly note that we have now addressed your concern. We have added the missing CAP CDS annotation to our document. It should start reflecting post our next release date. 

I will be closing this issue now. However, if you have any other concerns, please feel free to write back to us.

Thanks and regards,
Mishu Agrawal

**Comment by marianfoo** [comment]
Thanks Mishu!

**Pull request merged**
