### PR TITLE
Update enabling-editing-using-a-dialog-mass-edit-965ef5b.md

### PR DESCRIPTION
**Pull request by bkrencker**
Fields with Value Help with Fixed Values are restricted from Mass-Edit

### CODE REVIEW

**Comment by OlMue** [comment]
Hi @bkrencker, thanks for your contribution! We'll take a look and get back to you.

**Comment by mishuagrawal** [comment]
Hello @bkrencker, Thank you for reaching out to us. We are working on your concern and we will get back to you with an update soon.

**Comment by bkrencker** [comment]
Hi @OlMue / @mishuagrawal are there any updates on this?

**Comment by mishuagrawal** [comment]
Hello @bkrencker,

Thank you for your patience. Please know that we have now updated the document with the provided information. You can review the changes here: https://ui5.sap.com/#/topic/965ef5b2895641bc9b6cd44f1bd0eb4d

If in case you have any concerns, please feel free to write back to us. If your concern is resolved, please do let us know.

Thanks and regards.
Mishu Agrawal

**Comment by mishuagrawal** [comment]
Hello @bkrencker,

Please confirm if your concern is now resolved and if we can go ahead and close this request.

Thanks and regards,
Mishu Agrawal

**Comment by bkrencker** [comment]
> Thank you for your valuable content contribution, @bkrencker! So that we can [recognize your contribution in the SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please check your SAP Community user ID (this is a number) in your [personal settings page](https://community.sap.com/t5/user/myprofilepage/tab/personal-profile) and share it with us in a reply to this comment. Make sure you just include the number in the reply.
> 
> Your user ID is displayed as follows:
> 
> **Change display name for User ID N**
> 
> where N is your user ID. For example, [53 is the user ID of the user 'qmacro'](https://community.sap.com/t5/user/viewprofilepage/user-id/53).
> 
> Please note that we are currently refactoring our profile and badge system on the SAP Community, and will start assigning badges again when that's complete.

2161

**Comment by bkrencker** [comment]
Thanks

**Pull request closed without merging**
