### PR TITLE
Update step-26-mock-server-configuration-bae9d90.md

### PR DESCRIPTION
**Pull request by caiwenhn2008**
missing =>

### CODE REVIEW

**Comment by flovogt** [comment]
@caiwenhn2008 thanks for creating this issue. Using just a simple method definition should be fine here. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions 

Any benefits of using arrow function here?

**Comment by caiwenhn2008** [comment]
> @caiwenhn2008 thanks for creating this issue. Using just a simple method definition should be fine here. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions
> 
> Any benefits of using arrow function here?

Thanks for quick response, this is what i see from https://sapui5.hana.ondemand.com/sdk/#/topic/bae9d90d2e9c4206889368f04edab508 , and I failed when run the sample

image

is there any github synch issue here?  we can either remove ":" or change to  " init: () => {"
"

**Comment by caiwenhn2008** [comment]
Yes, nightly fixed, thanks!

**Comment by OlMue** [comment]
> @KlattG could you please check if the fix is also present in the last 1.120 version?

Just checked it, it's fixed in 1.120.2.

**Pull request closed without merging**
