### PR TITLE
[FIX] Remove duplicate words

### PR DESCRIPTION
**Pull request by boghyon**
Similar to https://github.com/SAP/openui5/commit/9311d7b0bf6b0df9c571506502455310c1a0f8e6, fixing duplicated words such as `the the `, `in in `, `is is `, `to to `, `about about `, etc. in the documentation.

### CODE REVIEW

**Comment by KvM2** [comment]
Thanks,@boghyon  , for your valuable contribution and your eye for detail. We appreciate and will look into it .

**Comment by boghyon** [comment]
@KvM2 Thanks Katja. Btw. the `is is ` case should've been corrected to <code><strong>it</strong> is </code>, but my initial commit simply removed the former `is ` part. Now I added the missing `it `, squashed the two commits into one, and pushed again. Everything should be correct now.

**Comment by boghyon** [comment]
Thanks, I guess I abandon this PR?

**Comment by KvM2** [comment]
That would be great. I think the conflict is just because I already edited some of the (source) files earlier. You could either resolve the conflict or even close it , which might be easier.

**Comment by boghyon** [comment]
@KvM2 Closed. How can we make PRs easier to merge in the future? Should we contribute changes in this [SAPUI5-docs](https://github.com/SAP-docs ) and in [OpenUI5-docs](https://github.com/SAP/openui5-docs) separately even if the OpenUI5 content can be found also in this repo?

**Comment by KvM2** [comment]
Hi Boghyon, I think using this repo should usually work. I assume this was a special situation with the large number of files that were part of your change, and because I couldn't make all the changes right away. If this occurs again, let's have a closer look.

**Comment by OlMue** [comment]
Hi @boghyon and @KvM2, just some additional food for thought on this:
- [OpenUI5-docs](https://github.com/SAP/openui5-docs) is the MD version of the **published** OpenUI5 documentation aimed at **external** OpenUI5 users
- [SAPUI5-docs](https://github.com/SAP-docs) is the MD version of the **published** SAPUI5 documentation aimed at **external** SAPUI5 users
- [https://github.wdf.sap.corp/UICS-Consumption/UI5-docs](https://github.wdf.sap.corp/UICS-Consumption/UI5-docs) is the MD version of the SAPUI5 documentation **currently in development** plus some internal content aimed at **internal** SAPUI5 users (and **available only internally** at SAP)

They're all based on the same DITA XML source, so it theoretically doesn't matter which repo you're using for PRs unless they're specific to SAPUI5/OpenUI5/internal content. If we implement the contribution in our DITA XML source, it will be changed in all three repos/outputs anyway. But since you're an SAP employee, the [third](https://github.wdf.sap.corp/UICS-Consumption/UI5-docs) repo might be better in certain cases because you can also have "internal" discussions there. I hope this makes sense. ;-)

**Pull request closed without merging**
