### PR TITLE
Update step-4-quick-filter-for-the-worklist-85ec3a9.md

### PR DESCRIPTION
**Pull request by distareza**
Fixing example code to align with previous step

### CODE REVIEW

**Comment by KvM2** [comment]
Hi @distareza, thanks for your contribution! We'll look into it and get back to you.

**Comment by LilyanaOviPe** [comment]
Hi @distareza, thanks for your contribution. Could you please give me some more details about the modification you're suggesting and what is the exact relationship with the previous step. 

Thanks a lot.

Best regards,
Lilyana

**Comment by distareza** [comment]
Hi @LilyanaOviPe,

I’ve noticed some differences between Source 1 and the provided source code. I’d like to make modifications to align it with the provided code.

Here are the sources for reference:

[Source 1](https://sapui5.hana.ondemand.com/#/topic/85ec3a9454ac4eb1a901745e773844d3)
[Source Code](https://sapui5.hana.ondemand.com/#/entity/sap.m.tutorial.worklist/sample/sap.m.tutorial.worklist.04/code)

image


I hope this makes sense! Let me know if you have any questions or thoughts.

Thanks! 😊

**Comment by LilyanaOviPe** [comment]
Hi @distareza, thanks a lot for the clarification. Yes, indeed the code in the documentation should be the same as the one in the sample. I'll make the necessary changes and they will be visible with the next release. 

Thanks again.

Best regards,
Lilyana

**Pull request merged**
