### PR TITLE
Update value-help-as-a-dropdown-list-2a0a630.md

### PR DESCRIPTION
**Pull request by tobiashofmann**
The closing tag for Record is missing. This resulted in a XML parser / validation error.

### CODE REVIEW

**Comment by JannaLisa** [comment]
Hello @tobiashofmann ,
I'm happy to correct the issue you're reported. At the moment I wouldn't be able to merge your pull request, however, since you need to sign the CLA first, please.
Could you please do this so I can work on this issue?
Thanks!

**Comment by tobiashofmann** [comment]
CLA is signed

**Comment by JannaLisa** [comment]
Hi @tobiashofmann ,
I've corrected this mistake. The change will be visible with release 1.111.
Thanks!

**Comment by tobiashofmann** [comment]
https://people.sap.com/tobias.hofmann

**Pull request merged**
