### PR TITLE
Update step-3-using-dynamic-page-for-the-list-view-0830bce.md

### PR DESCRIPTION
**Pull request by distareza**
add required missing code on "ui5.yaml" file

### CODE REVIEW

**Comment by KvM2** [comment]
Hi @distareza, thanks for your contribution! We'll look into it and get back to you.

**Comment by LilyanaOviPe** [comment]
Hi @distareza, thanks for your contribution. The 'ui5.yaml' file is tooling agnostic and maintaining such a file in the documentation is not practical as it will constantly change. What we can do instead is add a link to the UI5 Tooling documentation (https://sap.github.io/ui5-tooling/stable/) which will give the additional information you need.

I hope this helps. 

Best regards,
Lilyana

**Comment by flovogt** [comment]
I would recommend to align it with https://ui5.sap.com/#/topic/2680aa9b16c14a00b01261d04babbb39 where `ui5 init` command is used. The command will stay and the yaml is created with the best-in-class `ui5.yaml`

**Comment by LilyanaOviPe** [comment]
Hi @distareza, after discussing this with the development team, we've added a note regarding the ui5.yaml file. It will be visible with the upcoming official release. 

Thanks again for your contribution.
Best regards,
Lilyana

**Pull request merged**
