### PR TITLE
docs(FE): Fix CAP CDS annotation for LineItem

### PR DESCRIPTION
**Pull request by bugwelle**
A single quote was missing in the snippet.

### CODE REVIEW

**Comment by OlMue** [comment]
Hi @bugwelle, thanks a lot for pointing this out. We're on it.

**Comment by mishuagrawal** [comment]
Hello @bugwelle,

Thank you for reaching out to us. I have now corrected the document and the change should start reflecting with our upcoming release. Please let us know if there are any else we can help you with. 

Thanks and regards,
Mishu Agrawal

**Comment by bugwelle** [comment]
Thanks, @mishuagrawal . I take it that the change is handled outside of this PR and I can close it? :)

**Comment by mishuagrawal** [comment]
Hello @bugwelle, yes you are right. I have already fixed the document but the change reflection will take some time. If its alright with you, I can go ahead and merge this PR. 

Please let me know. Thank you!

**Comment by bugwelle** [comment]
@mishuagrawal Thanks! Whatever suites you best. If you can merge it, that'd be great. :)

**Comment by mishuagrawal** [comment]
Hello @bugwelle, 

Thank you for your confirmation. I will go ahead and merge the PR.

**Comment by bugwelle** [comment]
264793

**Pull request merged**
