### PR TITLE
Use `ext` as a folder name instead of `custom`

### PR DESCRIPTION
**Pull request by marianfoo**
It´s best practice to use the `ext` folder name instead of the old `custom`.
That's why I replaced the folder name everywhere where it was still `custom`.

### CODE REVIEW

**Comment by marianfoo** [comment]
I have just seen that there is already a PR for it.
If it is exactly the same changes, this PR can simply be closed.
#7

**Comment by OlMue** [comment]
Thanks a lot, @marianfoo !

Hi @JannaLisa
I guess this really is the same request as the one by Nicolas in #7, right?

**Comment by JannaLisa** [comment]
Hello @marianfoo and @OlMue ,
Yes, it looks like this is indeed the same issue.
So I hope it's fine that I merge this pull request, even if I haven't worked on the other one yet ;-)
But it's open and we agree it's the same To Do.
So thanks and I'll try to work on this ASAP.

**Comment by OlMue** [comment]
Resolved a conflict and finally merged. thanks again, @marianfoo!

**Comment by OlMue** [comment]
Sorry, my mistake, PR #7 is still open. Ignore this merge, content will be overwritten by the CMS source again. @JannaLisa, please give a short update on the progress of PR #7. Thanks! :-)

**Pull request merged**
