### PR TITLE
Update table-groupings-d344c5a.md

### PR DESCRIPTION
**Pull request by sani2608**
typo fix

### CODE REVIEW

**Comment by OlMue** [comment]
Hi @sani2608, thanks for your contribution! We're on it.

**Comment by sani2608** [comment]
> Thank you for your valuable content contribution, @sani2608! So that we can [recognize your contribution in the SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please check your SAP Community user ID (this is a number) in your [personal settings page](https://community.sap.com/t5/user/myprofilepage/tab/personal-profile) and share it with us in a reply to this comment. Make sure you just include the number in the reply.
> 
> Your user ID is displayed as follows:
> 
> **Change display name for User ID N**
> 
> where N is your user ID. For example, [53 is the user ID of the user 'qmacro'](https://community.sap.com/t5/user/viewprofilepage/user-id/53).
> 
> Please note that we are currently refactoring our profile and badge system on the SAP Community, and will start assigning badges again when that's complete.

831978

**Comment by KaijaInga** [comment]
Hi @sani2608 , the changes have been made, you can see them on Help Portal: https://help.sap.com/docs/SAPUI5/96880755e4e64fcd96c12694f430fece/d344c5aa5c81483482dbbed5b3abb142.html?state=DRAFT&q=table%20groupings 
Please check if everything's alright on your end and let me know if there's anything else we should check. If not, please close this pull request. Thank you!

**Comment by OlMue** [comment]
@KaijaInga, thanks! Just to let you know: Contributors from outside SAP can't access the draft Help Portal link you provided.

Since you corrected the typo, you can now merge this PR. external contributors don't have this authorization, and merging is the last step if we have accepted a contribution. Thanks! :-)

**Comment by KaijaInga** [comment]
Thanks, @OlMue ! I can't merge, though... 
image

**Comment by OlMue** [comment]
Hi @KaijaInga, right, I need to check your authorizations, sorry. I merged the PR in the meantime.

**Pull request merged**
