### PR TITLE
Update using-the-multi-input-field-on-the-object-page-04ff5b1.md

### PR DESCRIPTION
**Pull request by lemaiwo**
Example for ABAP CDS is missing. We tried this and it is working for us on UI5 version 1.96.6 (S/4HANA2021)

### CODE REVIEW

**Comment by KvM2** [comment]
Hi @lemaiwo  , thanks for your contribution. We appreciate it and will look into this.

**Comment by didzvein** [comment]
Hello, @lemaiwo , thanks for your contribution! We kindly ask you to sign the Contributor License Agreement as we cannot merge these changes without it.

**Comment by lemaiwo** [comment]
I would like to sign the license cla but I'm getting the message: There is no CLA to sign for SAP-docs/sapui5
Any idea what I'm doing wrong?

**Comment by OlMue** [comment]
> I would like to sign the license cla but I'm getting the message: There is no CLA to sign for SAP-docs/sapui5 Any idea what I'm doing wrong?

Hi Wouter, you're right, that's strange. It says "Bad Credentials". I'll investigate and get back to you. @didzvein: I'll check this.

**Comment by OlMue** [comment]
@lemaiwo, could you please check again? The CLA seems to be available again. Thanks for your patience!

**Comment by lemaiwo** [comment]
Done!

**Comment by didzvein** [comment]
Thank you, we're working on this, and we'll let you know when the changes are ready

**Review by stefan0816 — COMMENTED** [review]
I would slightly adjust the sample and add the name of the association, so that it gets clearer where to add the annotation. Also, in this case the type can be omitted. What do you think?

```
@UI: {  lineItem: [ { value: '_SupportedMaterials.Material', label: 'Supported Materials' } ] }  
_SupportedMaterials;
```

**Comment by lemaiwo** [comment]
You are right! Should I change this and commit the update?

**Comment by JannaLisa** [comment]
Hi @lemaiwo ,
If you know exactly what needs to be done and could do this, I think it would help us authors to process this quickly.
Thanks in advance!

**Comment by lemaiwo** [comment]
Changes are applied as mentioned by @stefan0816

**Pull request merged**
