### PR TITLE
Fix for small Copy and Paste Error in ABAP CDS Sample

### PR DESCRIPTION
**Pull request by DerGuteWolf**

### CODE REVIEW

**Comment by KvM2** [comment]
Hello , thanks for your contribution! We really appreciate it and will look into this .

**Comment by JannaLisa** [comment]
Hi @DerGuteWolf ,
This does indeed appear to be a mistake in our sample code.
Well spotted!
We will fix this and the corrected version will be visible with 1.109.
Thanks.

**Comment by didzvein** [comment]
Hello @DerGuteWolf,
thanks for your contribution. The sample code in documentation has been fixed, and it will be visible in 1.109.

**Comment by DerGuteWolf** [comment]
https://people.sap.com/wroeckelein.fum

**Pull request merged**
