### PR TITLE
new root view for FCL

### PR DESCRIPTION
**Pull request by MarcelWaechter**
the root view was moved. The old one still works in compatibility mode but is deprecated, therefore we should update it

### CODE REVIEW

**Comment by KvM2** [comment]
Hi @MarcelWaechter , thanks for your contribution. We appreciate it and will look into this.

**Comment by JannaLisa** [comment]
Hi @MarcelWaechter ,
I'll either do this myself ASAP or will ask a colleague to correct this.
Thanks for letting us know!

**Comment by didzvein** [comment]
Hello, @MarcelWaechter, thank you for your contribution! The topic has been updated and will be available as of 1.111

**Comment by OlMue** [comment]
Hi @MarcelWaechter, could you please sign the CLA? This would be great, otherwise we can't merge the PR. Thanks!

**Comment by MarcelWaechter** [comment]
https://people.sap.com/marcel.waechter

**Pull request merged**
