### PR TITLE
Add missing code fragment in sample based on customer feedback

### PR DESCRIPTION
**Pull request by lirudayam**

### CODE REVIEW

**Comment by KvM2** [comment]
Hi @lirudayam, thanks for your contribution. We appreciate it and will look into this.

**Comment by DivyaVD** [comment]
The topic is updated with the suggested changes.

**Comment by OlMue** [comment]
Hi @lirudayam, could you please sign the Contributor License Agreement (CLA)? Afterwards, we can merge your PR. Thanks! :-)

**Comment by lirudayam** [comment]
@OlMue done :-)

**Comment by lirudayam** [comment]
https://people.sap.com/leoirudayam

**Pull request merged**
